name: Compile Bicep to ARM Template

on:
  push:
    branches:
      - main  # Adjust the branch name as needed
  pull_request:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Bicep CLI
      run: |
        curl -Lo bicep https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64
        chmod +x ./bicep
        sudo mv ./bicep /usr/local/bin/bicep

    - name: Build ARM Template from Bicep
      run: |
        bicep build main.bicep

    - name: Upload ARM Template artifact
      uses: actions/upload-artifact@v2
      with:
        name: main-arm-template
        path: main.json